# Generated by Django 5.0 on 2023-12-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_product_created_at_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='İstanbul', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Ürün Adı', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
